//imports
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNav from '@/components/MainNav'
import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DB HOLDING TICKETING',
  description: 'Generated by Nikita Lázaro',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        <nav className="flex flex-col items-center border-b mb-5 px-5 py-3">
          <div className= "max-w-6x1 w-full">  
            <MainNav />
          </div>
        </nav>
        <main className="flex flex-col items-center">
          <div className= "max-w-6x1 w-full">
            {children}
          </div>
        </main>
      </ThemeProvider>
      </body>
    </html>
  )
}
